var constants = {
  RECEIVED_DOCTORS: 'RECEIVED_DOCTORS',
  RECEIVED_UPVOTES: 'RECEIVED_UPVOTES',
  RECEIVED_ONE_DOCTOR: 'RECEIVED_ONE_DOCTOR',
  DELETED_ONE_DOCTOR: 'DELETED_ONE_DOCTOR',
  EDITED_ONE_DOCTOR: 'EDITED_ONE_DOCTOR'
};

module.exports = constants;
